name: Iris Classifier

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12.3
      uses: actions/setup-python@v3
      with:
        python-version: "3.12.3"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run tests
      run: |
        python test.py
    - name: Make or detect changes
      run: |
        # Example: build documentation or modify files
        echo "Automating PR to main branch"
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        base: main
        branch: ${{ github.head_ref }}
        title: "Automated Pull Request to Main"
        body: "This pull request was created automatically via GitHub Actions."
        commit-message: "chore: auto-create PR to main"
