name: Iris Classifier

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12.3
      uses: actions/setup-python@v3
      with:
        python-version: "3.12.3"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run tests
      run: |
        python test.py
    - name: Generate diff
      run: |
      echo '```
      git diff metrics.csv >> diff_output.txt
      echo '```' >> diff_output.txt
      echo "diff_body<<EOF" >> $GITHUB_OUTPUT
      cat diff_output.txt >> $GITHUB_OUTPUT
      echo "EOF" >> $GITHUB_OUTPUT

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        base: main
        branch: ${{ github.head_ref }}
        title: "Automated PR to main"
        body: |
          This pull request includes the following changes:

          ${{ steps.diff.outputs.diff_body }}

